# This is a basic workflow to help you get started with Actions

name: Build Android Library AAR

on:
  push:
    branches:
      - main
  workflow_dispatch: 

jobs:
  build-aar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 11

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build Release AAR
        run: ./gradlew :your-library-module:assembleRelease

      - name: Upload AAR
        uses: actions/upload-artifact@v4
        with:
          name: your-library-aar
          path: your-library-module/build/outputs/aar/*.aar
